[package]
name = "tauri-plugin-printer-wkhtml-bin"
version = "0.1.2"
authors = ["Franco J. Ferreyra <ferreyrafranco0802@gmail.com>"]
description = "Tauri plugin for printer with embedded wkhtmltopdf for Windows"
edition = "2021"
license = "MIT"
repository = "https://github.com/FrancoJFerreyra/tauri-plugin-printer"
keywords = ["tauri", "plugin", "printer", "windows"]
categories = ["api-bindings", "development-tools"]
readme = "README.md"
links = "tauri-plugin-printer-wkhtml-bin"

exclude = ["/examples", "/dist-js", "/node_modules"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tauri = { version = "2.7.0" }
serde = "1.0"
thiserror = "2"
base64 = "0.22"
tempfile = "3.8"

[build-dependencies]
tauri-plugin = { version = "2.3.1", features = ["build"] }